// Narration for the solar system video.
export const SCRIPT = [
  'Welcome to a tiny solar system, built entirely from code.',
  'At the center burns a star, pouring light across the dark.',
  'Around it, worlds trace their paths in endless, quiet orbits.',
  'One wears rings of ice and dust, glittering as it turns.',
  'And the voice you hear? Generated by ElevenLabs.',
  'Three D motion, rendered frame by frame. Thanks for watching.',
];

export const MODEL_ID = 'eleven_v4';
export const LANGUAGE_CODE = 'en';

export const AMBIENCE = 'Deep, calm cinematic space ambience, soft low synth drone with gentle shimmering high pads, no melody';
export const SFX = [];
