// Step 1: generate narration (with word timestamps) and an ambient sound bed via ElevenLabs.
import { writeFileSync } from 'node:fs';

const KEY = process.env.ELEVENLABS_API_KEY;
if (!KEY) throw new Error('ELEVENLABS_API_KEY is not set');

const VOICE_ID = process.env.VOICE_ID || 'JBFqnCBsd6RMkjVDRZzb'; // George - warm storyteller
const API = 'https://api.elevenlabs.io/v1';

export const SCRIPT = [
  'Welcome to a tiny solar system, built entirely from code.',
  'At the center burns a star, pouring light across the dark.',
  'Around it, worlds trace their paths in endless, quiet orbits.',
  'One wears rings of ice and dust, glittering as it turns.',
  'And the voice you hear? Generated by ElevenLabs.',
  'Three D motion, rendered frame by frame. Thanks for watching.',
];

async function post(path, body) {
  const res = await fetch(`${API}${path}`, {
    method: 'POST',
    headers: { 'xi-api-key': KEY, 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  });
  if (!res.ok) throw new Error(`${path} -> ${res.status} ${await res.text()}`);
  return res;
}

// Narration with character-level alignment.
const tts = await (
  await post(`/text-to-speech/${VOICE_ID}/with-timestamps?output_format=mp3_44100_128`, {
    text: SCRIPT.join(' '),
    model_id: 'eleven_multilingual_v2',
    voice_settings: { stability: 0.5, similarity_boost: 0.75, style: 0.25 },
  })
).json();
writeFileSync('out/narration.mp3', Buffer.from(tts.audio_base64, 'base64'));

// Collapse character alignment into words.
const { characters, character_start_times_seconds: starts, character_end_times_seconds: ends } = tts.alignment;
const words = [];
let cur = null;
characters.forEach((ch, i) => {
  if (/\s/.test(ch)) { if (cur) words.push(cur), (cur = null); return; }
  if (!cur) cur = { text: '', start: starts[i], end: ends[i] };
  cur.text += ch;
  cur.end = ends[i];
});
if (cur) words.push(cur);

// Sentence boundaries = words ending in . ? !
const sentences = [];
let s = { start: words[0].start, words: [] };
for (const w of words) {
  s.words.push(w);
  if (/[.?!]$/.test(w.text)) { s.end = w.end; sentences.push(s); s = { start: null, words: [] }; }
  else if (s.start === null) s.start = w.start;
}
const duration = words[words.length - 1].end;
writeFileSync('out/timeline.json', JSON.stringify({ duration, sentences, words }, null, 2));
console.log(`narration: ${duration.toFixed(2)}s, ${words.length} words, ${sentences.length} sentences`);

// Ambient space bed (sound effect generation, max 30s per clip).
const sfx = await post('/sound-generation?output_format=mp3_44100_128', {
  text: 'Deep, calm cinematic space ambience, soft low synth drone with gentle shimmering high pads, no melody',
  duration_seconds: Math.min(30, Math.ceil(duration + 2)),
  prompt_influence: 0.5,
});
writeFileSync('out/ambience.mp3', Buffer.from(await sfx.arrayBuffer()));
console.log('ambience saved');
